In [1]:
import numpy as np
#dir(numpy)


In [2]:
a=np.array([1,2,3,5.68],dtype="int")
print(a)
type(a)

[1 2 3 5]


numpy.ndarray

In [3]:
b=np.array([1,2,3,5.68],dtype="float32")
b

array([1.  , 2.  , 3.  , 5.68], dtype=float32)

In [4]:
#nested lists multidimensioal arrays
np.array([[1,2,30],[2,4,8],[8,8,5]])


array([[ 1,  2, 30],
       [ 2,  4,  8],
       [ 8,  8,  5]])

In [5]:
x=np.array([[[1,2,3],[4,56,8]],[[5,7,8],[5,6,2]]])
x

array([[[ 1,  2,  3],
        [ 4, 56,  8]],

       [[ 5,  7,  8],
        [ 5,  6,  2]]])

In [6]:
#create a length-10 interger array filled with zeros
print(np.zeros(10))
print(np.zeros((2,4)))
print(np.zeros((3,5)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [7]:
a=np.ones(4)
print(a)
print(np.ones((2,3)))
print(np.ones((3,5,4)))
print(np.full((3,2),99))

[1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
[[99 99]
 [99 99]
 [99 99]]


In [8]:
list(range(0,10,2))

[0, 2, 4, 6, 8]

In [9]:
#Create an array filled with a linear sequence
# Starting at 0, ending at 1, stepping by 0.2
#(this is simmilar to the built-in-range() function)
np.arange(0,1,0.2) #similar to seq command in R

array([0. , 0.2, 0.4, 0.6, 0.8])

In [10]:
#create an array of five values evenly spaced between 0 and 1
print(np.linspace(0,1,5))

print(np.linspace(-1,100,10))

[0.   0.25 0.5  0.75 1.  ]
[ -1.          10.22222222  21.44444444  32.66666667  43.88888889
  55.11111111  66.33333333  77.55555556  88.77777778 100.        ]


# Simple random data

In [11]:
#random number between 0 to 1
np.random.rand(15)

array([0.87646247, 0.27089597, 0.71978902, 0.84624728, 0.25647964,
       0.71418154, 0.11397043, 0.92057649, 0.05796975, 0.77083359,
       0.26103995, 0.20594062, 0.661469  , 0.80300346, 0.84668315])

In [12]:
#2 dimensional array
np.random.rand(10,2)

array([[0.03668751, 0.09313623],
       [0.81146588, 0.37867155],
       [0.10671932, 0.60816911],
       [0.72722876, 0.9267876 ],
       [0.72721869, 0.75171338],
       [0.46974175, 0.3940897 ],
       [0.36235761, 0.79241733],
       [0.80052543, 0.21760624],
       [0.83792053, 0.23382946],
       [0.94226856, 0.03845822]])

In [13]:
np.random.rand(10,1,3)

array([[[0.45893186, 0.11244982, 0.65870156]],

       [[0.51507481, 0.42431696, 0.41154621]],

       [[0.02272035, 0.56155049, 0.19947588]],

       [[0.04864472, 0.89259222, 0.41941247]],

       [[0.68873935, 0.89897902, 0.09288565]],

       [[0.60680385, 0.49236743, 0.65917865]],

       [[0.94981076, 0.63400443, 0.10779931]],

       [[0.92151999, 0.57383853, 0.06733603]],

       [[0.81301077, 0.41218091, 0.24953499]],

       [[0.09081557, 0.28221431, 0.00296658]]])

In [14]:
np.random.randn(10)

array([ 0.07590674, -0.18647442,  1.21714142, -0.65452127, -0.64602577,
       -0.94919983,  0.86734271, -0.89597269,  0.59935084, -1.65606758])

In [15]:
#np.random.randn() gives sample from standard normal distribution
np.random.randn(10,2)

array([[-0.49907527,  0.2924325 ],
       [-0.30815053,  2.00318706],
       [ 0.44423305, -0.46844024],
       [ 0.50953831, -0.66791424],
       [ 1.79793002,  0.30909728],
       [-0.06405408,  2.21491758],
       [ 2.75489012,  0.09652311],
       [ 0.15852417, -1.55637956],
       [ 0.84675711, -0.00458782],
       [ 1.10430601,  1.89477594]])

In [16]:
np.random.randn(10,2,3)

array([[[ 0.83957265, -0.81238032, -0.62220076],
        [ 0.23599817, -0.71409954,  0.40477169]],

       [[ 0.07057095,  0.67805979, -1.79730285],
        [-0.76637693, -0.98391878, -2.0675325 ]],

       [[-0.25302283, -0.07386965, -0.03473721],
        [ 0.80726425,  1.00983879,  0.91034882]],

       [[ 0.35308863, -0.34150292,  2.28416956],
        [ 0.40998235,  0.10876271,  0.41921341]],

       [[-1.02189141, -0.91380838, -1.90815638],
        [ 1.65370498,  0.9298779 , -0.670466  ]],

       [[-0.20903821,  1.24680888, -1.38395994],
        [ 2.24446642,  0.19081238, -0.37270272]],

       [[ 0.03983866,  0.55521147, -0.21565187],
        [ 1.65272948,  0.50861158, -0.59889821]],

       [[-0.12449822, -0.20680464, -0.51077222],
        [ 0.50236139,  2.68731034,  0.02685854]],

       [[-0.9290858 ,  0.39915413,  0.60664545],
        [-1.76057623, -1.03976941,  0.54145253]],

       [[-1.12827088,  0.37048594,  1.56279178],
        [ 0.87317022,  1.38812674,  0.26750297]]])

In [17]:
#np.random.randint(low,high,size,dtype)
#This function of random module is used to generate random integer from inclusive(low) to exclusive(high).
np.random.randint(2)

1

In [18]:
np.random.randint(10,15,(3,4))

array([[14, 14, 10, 13],
       [13, 12, 11, 14],
       [10, 12, 12, 14]])

In [19]:
np.random.random(10)
#it gives random number from  to 1.

array([0.72983108, 0.53413051, 0.69228897, 0.34847952, 0.6079851 ,
       0.36896841, 0.81778384, 0.78852775, 0.24180951, 0.60835175])

In [20]:
np.random.random((3,2,5))

array([[[0.93710273, 0.59852346, 0.36445299, 0.10648904, 0.2772503 ],
        [0.09400826, 0.19031891, 0.71269914, 0.69282228, 0.04274307]],

       [[0.12853116, 0.63673005, 0.6941013 , 0.0124509 , 0.01694781],
        [0.97797916, 0.72792811, 0.8904258 , 0.40077873, 0.96637324]],

       [[0.84753516, 0.51985405, 0.39360067, 0.23124027, 0.78346438],
        [0.17308816, 0.84173189, 0.68960887, 0.08547492, 0.61586544]]])

In [21]:
#choice(a,size=None,replace=True,p=None) 
#similar to sample command in R
x=np.array(["JK","RM","JIN",'SUGA'])
a=np.random.choice(x,size=2,replace=False)
a

array(['JK', 'JIN'], dtype='<U4')

In [22]:
np.random.choice(x,(3,10,2),True)

array([[['RM', 'RM'],
        ['JIN', 'JIN'],
        ['SUGA', 'SUGA'],
        ['RM', 'RM'],
        ['JIN', 'RM'],
        ['SUGA', 'JK'],
        ['SUGA', 'RM'],
        ['JK', 'SUGA'],
        ['SUGA', 'JK'],
        ['SUGA', 'RM']],

       [['JIN', 'JIN'],
        ['JIN', 'RM'],
        ['JIN', 'JIN'],
        ['RM', 'RM'],
        ['JK', 'JIN'],
        ['RM', 'JIN'],
        ['JIN', 'JK'],
        ['JK', 'JK'],
        ['JK', 'JIN'],
        ['JIN', 'JIN']],

       [['SUGA', 'JIN'],
        ['RM', 'RM'],
        ['JIN', 'JIN'],
        ['JIN', 'JIN'],
        ['JK', 'RM'],
        ['SUGA', 'JK'],
        ['JK', 'RM'],
        ['JIN', 'SUGA'],
        ['JIN', 'JIN'],
        ['JK', 'JIN']]], dtype='<U4')

In [23]:
np.random.choice(x,(2,3),1,p=(0.3,0.4,0.2,0.1))

array([['RM', 'RM', 'JK'],
       ['JIN', 'JIN', 'RM']], dtype='<U4')

# permutation

In [24]:
x=np.array(["JK","RM","JIN",'SUGA',"JIMIN","V","JHOPE"])
x

array(['JK', 'RM', 'JIN', 'SUGA', 'JIMIN', 'V', 'JHOPE'], dtype='<U5')

In [25]:
np.random.permutation(x)

array(['SUGA', 'RM', 'JK', 'JIMIN', 'JHOPE', 'V', 'JIN'], dtype='<U5')

In [26]:
print(np.random.shuffle(x))
print(x)

None
['RM' 'JHOPE' 'JIN' 'JK' 'V' 'JIMIN' 'SUGA']


In [27]:
#binomial(n,p,size)
np.random.binomial(5,0.3,(3,2))

array([[1, 2],
       [1, 2],
       [2, 3]])

In [28]:
#np.random.chisquare(df,size)
np.random.chisquare(3,(4,2,5,4))

array([[[[ 2.46478664,  4.82463901,  9.07632139,  4.25722469],
         [ 0.61270529,  5.18297586,  9.69037327,  0.71096278],
         [ 2.84586768,  0.53210277, 10.58118901,  3.88768435],
         [ 0.8492207 ,  1.03586913,  3.52095461,  4.10520938],
         [ 1.82674694,  1.50742601,  3.33445575,  2.12578772]],

        [[ 2.0210092 ,  2.79308014,  6.51615679,  1.18943129],
         [ 0.88032523,  5.08112372,  0.46931792,  0.51158567],
         [ 2.96062261,  0.32701516,  1.83208356,  6.67615487],
         [ 0.38538119,  7.81953402,  1.60355307,  2.66467806],
         [ 0.0903529 ,  1.98221641,  0.39785685,  1.73486569]]],


       [[[ 0.5472386 ,  2.72511072,  1.40909384,  6.60881687],
         [ 1.5712612 ,  1.26435628,  2.06598287,  1.65393082],
         [ 1.07666458,  3.9003164 ,  2.53541592,  2.49678529],
         [ 2.04613897,  1.54058456,  5.66297344,  2.48304631],
         [11.23504735,  6.55223032,  4.02313549,  3.00372665]],

        [[ 0.87441488,  0.96719584,  4.47976304

In [29]:
#np.exponential(scale,shape)
np.random.exponential(2,5)

array([3.77028703, 0.18591567, 0.71931084, 7.31103372, 0.30547994])

In [30]:
print(np.random.normal())
print(np.random.normal(0,1,10))

-0.2472861521498157
[ 0.72587873 -0.5117591  -1.05558938  1.7971567   0.51140632  2.06086942
  1.61123921 -1.02352386  1.41530205 -0.73554345]


In [31]:
print(np.random.normal(0,1,(2,5)))

[[-0.71104437  0.87901968 -0.84177335  0.32013347 -0.55633458]
 [-0.48944841  0.10876231 -2.05552046 -1.48590364 -0.64907307]]


In [32]:
x

array(['RM', 'JHOPE', 'JIN', 'JK', 'V', 'JIMIN', 'SUGA'], dtype='<U5')

In [33]:
from numpy.random import choice
choice(x,3,replace=False)

array(['V', 'JK', 'JIMIN'], dtype='<U5')

In [34]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Numpy array attributes 

In [35]:
a=np.random.randint(10,size=10)
b=np.random.randint(10,size=(2,10))
c=np.random.randint(10,size=(2,3,4))
print(a)
print(b)
print(c)

[2 1 7 7 6 0 6 1 2 2]
[[7 4 3 8 8 0 4 2 3 4]
 [2 4 0 1 3 6 7 6 1 1]]
[[[1 9 7 6]
  [0 8 4 3]
  [8 1 9 6]]

 [[8 1 2 1]
  [1 6 6 6]
  [3 2 3 0]]]


In [36]:
print(a.ndim) # gives the dimension
print(b.ndim)
print(c.ndim)

print(a.shape) #shape of array
print(c.shape)

print(a.size) #total number of elements
print(c.size)
print(b.dtype) #for data type
print(a.itemsize,"bytes") # memory size in byte of reach element in array.

1
2
3
(10,)
(2, 3, 4)
10
24
int32
4 bytes


# Array Indexing

In [37]:
print(a)
print(a[0])
print("length of a: ", len(a))
print(a[10])

[2 1 7 7 6 0 6 1 2 2]
2
length of a:  10


IndexError: index 10 is out of bounds for axis 0 with size 10

In [38]:
print(a[9])

2


In [39]:
a[-1]

2

In [40]:
print(b)
print(b[1,0])
b[0,0]=12
print(b)

[[7 4 3 8 8 0 4 2 3 4]
 [2 4 0 1 3 6 7 6 1 1]]
2
[[12  4  3  8  8  0  4  2  3  4]
 [ 2  4  0  1  3  6  7  6  1  1]]


In [41]:
b[0,0]=3.4568 # this will be truncated!
print(b)

[[3 4 3 8 8 0 4 2 3 4]
 [2 4 0 1 3 6 7 6 1 1]]


# Array Slicing: Accessing Subarrays

In [42]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
print(x[:5])
print(x[5:])
print(x[2:5])
print(x[::2])
print(x[0::2])

[0 1 2 3 4]
[5 6 7 8 9]
[2 3 4]
[0 2 4 6 8]
[0 2 4 6 8]


In [44]:
print(b)

[[3 4 3 8 8 0 4 2 3 4]
 [2 4 0 1 3 6 7 6 1 1]]


In [45]:
print(b[:2,:3])# two row, three column

[[3 4 3]
 [2 4 0]]


In [46]:
print(b[:1,::2])#first row, every other column

[[3 3 8 4 3]]


In [47]:
b[::-1,::-1] #subarray dimensions can even be reversed together

array([[1, 1, 6, 7, 6, 3, 1, 0, 4, 2],
       [4, 3, 2, 4, 0, 8, 8, 3, 4, 3]])

In [48]:
print(b[:,0]) #first column only
print(b[0,:]) #first row only
print(b[0]) # equivalent to the b[0,:]

[3 2]
[3 4 3 8 8 0 4 2 3 4]
[3 4 3 8 8 0 4 2 3 4]


#subarrays as no-copy views= one important and extremely useful thing to know aboutarray slices is that return views rather than copies of the array data. This is one area in which numpy array slicing diffes from python list slicing, in list slices will copies. Considerour two-dimensional array from before:

In [49]:
y=np.random.randint(10,size=(3,8))
y

array([[0, 7, 4, 9, 9, 3, 7, 7],
       [7, 7, 1, 6, 0, 1, 3, 1],
       [7, 1, 9, 1, 1, 7, 6, 6]])

In [50]:
y_sub=y[:2,:2]
y_sub

array([[0, 7],
       [7, 7]])

In [51]:
y_sub[0,0]=99
print(y_sub)
print(y)

[[99  7]
 [ 7  7]]
[[99  7  4  9  9  3  7  7]
 [ 7  7  1  6  0  1  3  1]
 [ 7  1  9  1  1  7  6  6]]


#Despite the nice features of array views, it is somtimes useful to in stead explicitly copy the data within acn array or a subarray. This can be mst easily done with the copy() method:

In [52]:
y_sub_copy=y[:2,:2].copy()
y_sub_copy[0,0]=44
print(y_sub_copy)
print(y)

[[44  7]
 [ 7  7]]
[[99  7  4  9  9  3  7  7]
 [ 7  7  1  6  0  1  3  1]
 [ 7  1  9  1  1  7  6  6]]


# Reshaping of Arrays

In [53]:
a=np.arange(1,10)
print(a)
b=a.reshape((3,3))
b

[1 2 3 4 5 6 7 8 9]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
x=np.array([1,2,3])
#row vector via reshape
print(x.reshape((1,3)))
print(x)
print(x.shape)

[[1 2 3]]
[1 2 3]
(3,)


In [55]:
#column vector via newaxis
print(x[:,np.newaxis])
x.shape

[[1]
 [2]
 [3]]


(3,)

# Array concatenation and Splitting

In [56]:
x=np.array([1,2,3])
y=np.array([3,2,1])
np.concatenate((x,y))

array([1, 2, 3, 3, 2, 1])

In [57]:
grid=np.array([[1,2,3],[4,5,6]])
print(grid)
np.concatenate([grid,grid])

[[1 2 3]
 [4 5 6]]


array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [58]:
x=np.array([1,2,3])
grid=np.array([[9,8,7],[6,5,4]])
# vertically stack the arrays
np.vstack([x,grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [59]:
#horizontal stack require same dimensions
x=np.array([[1,2,3],[99,99,99]])
grid=np.array([[9,8,7],[6,5,4]])
#horizontally stack the arrays
np.hstack([x,grid])

array([[ 1,  2,  3,  9,  8,  7],
       [99, 99, 99,  6,  5,  4]])

In [60]:
#splitting of array
x=[1,2,3,99,99,3,2,1]
a,b,c=np.split(x,[2,5])
print(a,b,c)

[1 2] [ 3 99 99] [3 2 1]


In [61]:
grid=np.arange(16).reshape((4,4))
print(grid)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [62]:
upper, lower =np.vsplit(grid,[2])
print("upper\n",upper)
print("lower\n",lower)
left, right=np.hsplit(grid,[2])
print(left)
print(right)

upper
 [[0 1 2 3]
 [4 5 6 7]]
lower
 [[ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


# Exploring Numpy's universal function

ufuncs exist in two flavors: unary  ufuncs, binary ufuncs

In [63]:
x=np.arange(4)
print(x)
print("x+5=",x+5)
print("x//2=",x//2) #floor division
print(np.add(x,2))


[0 1 2 3]
x+5= [5 6 7 8]
x//2= [0 0 1 1]
[2 3 4 5]


In [64]:
x=np.array([-2,-6,5,2,-6])
np.absolute(x)

array([2, 6, 5, 2, 6])

In [65]:
print(Out)

{2: <class 'numpy.ndarray'>, 3: array([1.  , 2.  , 3.  , 5.68], dtype=float32), 4: array([[ 1,  2, 30],
       [ 2,  4,  8],
       [ 8,  8,  5]]), 5: array([[[ 1,  2,  3],
        [ 4, 56,  8]],

       [[ 5,  7,  8],
        [ 5,  6,  2]]]), 8: [0, 2, 4, 6, 8], 9: array([0. , 0.2, 0.4, 0.6, 0.8]), 11: array([0.87646247, 0.27089597, 0.71978902, 0.84624728, 0.25647964,
       0.71418154, 0.11397043, 0.92057649, 0.05796975, 0.77083359,
       0.26103995, 0.20594062, 0.661469  , 0.80300346, 0.84668315]), 12: array([[0.03668751, 0.09313623],
       [0.81146588, 0.37867155],
       [0.10671932, 0.60816911],
       [0.72722876, 0.9267876 ],
       [0.72721869, 0.75171338],
       [0.46974175, 0.3940897 ],
       [0.36235761, 0.79241733],
       [0.80052543, 0.21760624],
       [0.83792053, 0.23382946],
       [0.94226856, 0.03845822]]), 13: array([[[0.45893186, 0.11244982, 0.65870156]],

       [[0.51507481, 0.42431696, 0.41154621]],

       [[0.02272035, 0.56155049, 0.19947588]],

       [

In [66]:
#Exponents and logaritms
x=[1,2,3]
print("x=",x)
print("e^x=",np.exp(x))
print("2^x=",np.exp2(x))
print("3^x=",np.power(3,x))
print("3^x=",np.power(x,3))
print("ln(x)=",np.log(x))
print("log2(x)=",np.log2(x))
print("log10(x)=",np.log10(x))

x= [1, 2, 3]
e^x= [ 2.71828183  7.3890561  20.08553692]
2^x= [2. 4. 8.]
3^x= [ 3  9 27]
3^x= [ 1  8 27]
ln(x)= [0.         0.69314718 1.09861229]
log2(x)= [0.        1.        1.5849625]
log10(x)= [0.         0.30103    0.47712125]


In [67]:
x=np.arange(1,6)
print(x)
print(np.add.reduce(x)) #addition of every value
print(np.sum(x))
print(np.multiply.reduce(x))
print(np.cumsum(x)) #for cummulative sum
print(np.cumprod(x)) # for cummulative product

[1 2 3 4 5]
15
15
120
[ 1  3  6 10 15]
[  1   2   6  24 120]


In [68]:
#outer products
x=np.arange(1,6)
print(x)
print(np.multiply.outer(x,x))
print(np.add.outer(x,x))

[1 2 3 4 5]
[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]]
[[ 2  3  4  5  6]
 [ 3  4  5  6  7]
 [ 4  5  6  7  8]
 [ 5  6  7  8  9]
 [ 6  7  8  9 10]]


In [69]:
#computation on Arrays: Broadcasting

In [70]:
a=np.array([1,5,9])
b=np.array([7,5,3])
print(a+b)
print(a+5)
c=np.array([5,5,5])
c+2

[ 8 10 12]
[ 6 10 14]


array([7, 7, 7])

In [71]:
m=np.ones((3,3))
print(m)
print("\n ans\n",m+a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

 ans
 [[ 2.  6. 10.]
 [ 2.  6. 10.]
 [ 2.  6. 10.]]


In [72]:
a=np.arange(3)
b=np.arange(3)[:,np.newaxis]
print(a)
print(b)

[0 1 2]
[[0]
 [1]
 [2]]


In [73]:
a+b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

# Comparison, masks, and boolean logic

In [74]:
x=np.array([1,5,9,7,8,4,5,8,3])
print(x<=3)
print((2*3)==(x**2))
print(2*x)
print(x**2)
print((x**2)==4)

[ True False False False False False False False  True]
[False False False False False False False False False]
[ 2 10 18 14 16  8 10 16  6]
[ 1 25 81 49 64 16 25 64  9]
[False False False False False False False False False]


In [75]:
#how many less than 6?
x=np.array([1,5,6,4,8,1,2,3,8,4,7,6])
print(np.count_nonzero(x<6))
print(np.sum(x<6))

7
7


In [76]:
#are there any values greater than 8?
np.any(x>8)

False

In [77]:
np.all(x<=8)

True

In [78]:
x=np.array([1,2,3,4,5,8,9,7,3])
np.sum((x>2) & (x<6))

4

In [79]:
x[x<5]

array([1, 2, 3, 4, 3])

# fancy indexing

In [80]:
x=np.random.randint(100,size=10)
print(x)
[x[5],x[8],x[2],x[3]]

[23 45 98 64 51 59 49 18 17 57]


[59, 17, 98, 64]

In [81]:
ind=[2,5,8]
x[ind]

array([98, 59, 17])

In [82]:
x=np.arange(12).reshape((3,4))
print(x)
row=np.array([2,1,0])
col=np.array([1,0,3])
x[row,col]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([9, 4, 3])

In [83]:
x=np.arange(10)
print(x)
i=np.array([2,8,7,4])
x[i]=999
print(x)
x[i]-=10
print(x)

[0 1 2 3 4 5 6 7 8 9]
[  0   1 999   3 999   5   6 999 999   9]
[  0   1 989   3 989   5   6 989 989   9]


# sorting arrays

In [84]:
x=np.array([2,5,7,1,4,6])
print(x)
print(np.sort(x)) #ascending
print(np.sort(x)[::-1]) #descending

[2 5 7 1 4 6]
[1 2 4 5 6 7]
[7 6 5 4 2 1]


In [85]:
x=np.array([25,30,20])
print(x)
print(np.argsort(x))

[25 30 20]
[2 0 1]


In [86]:
x=np.random.randint(0,10,(6,4))
print(x)

[[6 9 6 7]
 [5 2 3 5]
 [0 2 1 0]
 [2 4 5 6]
 [4 1 9 3]
 [7 5 2 4]]


In [87]:
np.sort(x)

array([[6, 6, 7, 9],
       [2, 3, 5, 5],
       [0, 0, 1, 2],
       [2, 4, 5, 6],
       [1, 3, 4, 9],
       [2, 4, 5, 7]])

In [88]:
np.sort(x,axis=0) #sort each column of x


array([[0, 1, 1, 0],
       [2, 2, 2, 3],
       [4, 2, 3, 4],
       [5, 4, 5, 5],
       [6, 5, 6, 6],
       [7, 9, 9, 7]])

In [89]:
np.sort(x,axis=1) #sort each row of x

array([[6, 6, 7, 9],
       [2, 3, 5, 5],
       [0, 0, 1, 2],
       [2, 4, 5, 6],
       [1, 3, 4, 9],
       [2, 4, 5, 7]])

In [90]:
x[:,1]

array([9, 2, 2, 4, 1, 5])

In [91]:
print(x)
x[:,1].argsort()

[[6 9 6 7]
 [5 2 3 5]
 [0 2 1 0]
 [2 4 5 6]
 [4 1 9 3]
 [7 5 2 4]]


array([4, 1, 2, 3, 5, 0], dtype=int64)

In [92]:
x[x[:,1].argsort()]

array([[4, 1, 9, 3],
       [5, 2, 3, 5],
       [0, 2, 1, 0],
       [2, 4, 5, 6],
       [7, 5, 2, 4],
       [6, 9, 6, 7]])

In [93]:
x[:,x[2,:].argsort()]

array([[6, 7, 6, 9],
       [5, 5, 3, 2],
       [0, 0, 1, 2],
       [2, 6, 5, 4],
       [4, 3, 9, 1],
       [7, 4, 2, 5]])

# Structured Data:Numpy's Structured Arrays

while often our data can well represented by homogenous array of values, sometimes this is not the case. This section demonstrates the use of the Numpy's structured arrays and record arrays, which provide efficient storage for compound, heterogeneous data. for example impage that we have several categories of data on a number of pepole (says, name, age,weight) and we'd like to store these values for use in a python pprogram. It would be possible to store these in three sepaeate arrays:

In [94]:
name=["JK","JIMIN","V","JIN","SUGA","JHOPE","RM"]
age=[25,27,27,30,29,28,28]
weight=[70,62,68,65,64,65,70]

In [95]:
#use a compound data type for structured arrays
data=np.zeros(7,dtype={'names':("name","age","weight"),
                       "formats":("U10","i4","f8")})
data

array([('', 0, 0.), ('', 0, 0.), ('', 0, 0.), ('', 0, 0.), ('', 0, 0.),
       ('', 0, 0.), ('', 0, 0.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [96]:
data['name']=name
data['age']=age
data['weight']=weight
print(data)

[('JK', 25, 70.) ('JIMIN', 27, 62.) ('V', 27, 68.) ('JIN', 30, 65.)
 ('SUGA', 29, 64.) ('JHOPE', 28, 65.) ('RM', 28, 70.)]


In [97]:
#Get all names
print(data['name'])
print(data[0])
#Get names where age is under 28
print(data[data['age']<28])
print(data[data['age']<28]['name'])

['JK' 'JIMIN' 'V' 'JIN' 'SUGA' 'JHOPE' 'RM']
('JK', 25, 70.)
[('JK', 25, 70.) ('JIMIN', 27, 62.) ('V', 27, 68.)]
['JK' 'JIMIN' 'V']


In [98]:
np.sort(data,order=['age'])[::-1]

array([('JIN', 30, 65.), ('SUGA', 29, 64.), ('RM', 28, 70.),
       ('JHOPE', 28, 65.), ('V', 27, 68.), ('JIMIN', 27, 62.),
       ('JK', 25, 70.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [99]:
# n random observation from B(p)
n=10
p=0.3
x=np.empty(n)
for  i in range(n):
    u=np.random.random()
    if u<p:
        x[i]=1
    else:
        x[i]=0
x

array([0., 1., 1., 1., 1., 0., 1., 0., 0., 1.])

In [100]:
# m random obsevation from B(n,p)
m=20
n=10
p=0.5
x=np.zeros(m)
for j in range(m):
    for i in range(n):
        u=np.random.random()
        if u<p:
            x[j]=x[j]+1
x

array([6., 5., 8., 6., 5., 3., 3., 5., 7., 3., 5., 6., 6., 4., 6., 5., 6.,
       7., 5., 3.])

In [101]:
#single observation from p(lm)

x=-1
lm=0.5
p=1
a=np.exp(-lm)
while p>a:
    u=np.random.random()
    p*=u
    x+=1
x

0