In [1]:
a="I am Aishwarya Vitthal Raut."

In [2]:
a.capitalize()

'I am aishwarya vitthal raut.'

In [3]:
a.upper()

'I AM AISHWARYA VITTHAL RAUT.'

In [4]:
a.lower()

'i am aishwarya vitthal raut.'

In [5]:
a.title()

'I Am Aishwarya Vitthal Raut.'

In [6]:
a.casefold()

'i am aishwarya vitthal raut.'

In [7]:
a.center()

TypeError: center expected at least 1 argument, got 0

In [8]:
a.center(50)

'           I am Aishwarya Vitthal Raut.           '

In [9]:
a.center(50,"@")

'@@@@@@@@@@@I am Aishwarya Vitthal Raut.@@@@@@@@@@@'

In [10]:
a.count("a")

5

In [11]:
a.count("r")

1

In [12]:
a.endswith("aut.")

True

In [13]:
a.endswith("xyz")

False

In [14]:
a.startswith("I am")

True

In [15]:
a.find("h")

8

In [16]:
a.find("a")

2

In [17]:
a.find("Aishwarya")

5

In [18]:
a.find("z")

-1

In [19]:
a.replace("Raut","raut")

'I am Aishwarya Vitthal raut.'

In [20]:
a.replace("raut","Raut")

'I am Aishwarya Vitthal Raut.'

In [21]:
a.split()

['I', 'am', 'Aishwarya', 'Vitthal', 'Raut.']

In [22]:
type(a.split())

list

In [23]:
b="I am Aishwarya, I am from Phaltan, Phaltan is in a Satara."

In [24]:
b.split()

['I',
 'am',
 'Aishwarya,',
 'I',
 'am',
 'from',
 'Phaltan,',
 'Phaltan',
 'is',
 'in',
 'a',
 'Satara.']

In [25]:
"_".join(a)

'I_ _a_m_ _A_i_s_h_w_a_r_y_a_ _V_i_t_t_h_a_l_ _R_a_u_t_.'

In [26]:
a.isdigit()

False

In [27]:
h="    Dept     of      stat     "
h

'    Dept     of      stat     '

In [28]:
len(h)

30

In [29]:
print(h)

    Dept     of      stat     


In [30]:
print(h.strip())

Dept     of      stat


In [31]:
print(h.lstrip())

Dept     of      stat     


In [32]:
print(h.rstrip())

    Dept     of      stat


In [33]:
g=h.strip()

In [34]:
len(g)

21

In [35]:
i="Aishwarya Raut"

In [36]:
g+" "+i

'Dept     of      stat Aishwarya Raut'

In [37]:
g+" "+2+" "+i

TypeError: can only concatenate str (not "int") to str

In [38]:
g+" "+str(2)+" "+i

'Dept     of      stat 2 Aishwarya Raut'

In [39]:
i.isdigit()

False

In [40]:
i.__contains__("a")

True

In [41]:
i.__contains__("shwa")

True

In [44]:
input_str1=input("Please enter first input string\n")

Please enter first input string
52


In [43]:
input_str2=input("Please enter second string\n")

Please enter second string
52


In [45]:
print("My name is {0}".format("Aish"))

My name is Aish


In [46]:
print("I like {0} and {1}".format("java","Python"))

I like java and Python


In [47]:
print("I like {1} and {0}".format("java","Python"))

I like Python and java


In [48]:
print("{name} is the {job} of {company}".format(name="Aish",job="ABC",company="TTT"))

Aish is the ABC of TTT


List

In [49]:
a=["Aishwarya",7522952325,2020060669,"Statistics"]
b=["Paltan",415523,"Satara","Maharashtra"]


In [50]:
print(a)
b

['Aishwarya', 7522952325, 2020060669, 'Statistics']


['Paltan', 415523, 'Satara', 'Maharashtra']

In [51]:
type(a) and type(b)

list

In [52]:
a+b

['Aishwarya',
 7522952325,
 2020060669,
 'Statistics',
 'Paltan',
 415523,
 'Satara',
 'Maharashtra']

In [53]:
a*3


['Aishwarya',
 7522952325,
 2020060669,
 'Statistics',
 'Aishwarya',
 7522952325,
 2020060669,
 'Statistics',
 'Aishwarya',
 7522952325,
 2020060669,
 'Statistics']

In [54]:
a is b

False

In [55]:
a[0]

'Aishwarya'

In [56]:
a[-1]

'Statistics'

In [57]:
type(a[2])

int

In [58]:
a[:]

['Aishwarya', 7522952325, 2020060669, 'Statistics']

In [59]:
a[1:]

[7522952325, 2020060669, 'Statistics']

In [60]:
del a[0]

In [61]:
a

[7522952325, 2020060669, 'Statistics']

In [62]:
a.append("Aishwarya")

In [63]:
a

[7522952325, 2020060669, 'Statistics', 'Aishwarya']

In [64]:
x=a.copy()

In [65]:
x

[7522952325, 2020060669, 'Statistics', 'Aishwarya']

In [66]:
a

[7522952325, 2020060669, 'Statistics', 'Aishwarya']

In [67]:
a.count("Aishwarya")

1

In [68]:
gen=["F","M","F","M","M","M","F"]

In [69]:
gen.count("M")

4

In [70]:
gen.count("F")

3

In [71]:
a.extend(gen)
print(a)

[7522952325, 2020060669, 'Statistics', 'Aishwarya', 'F', 'M', 'F', 'M', 'M', 'M', 'F']


In [72]:
a.index("M")

5

In [73]:
print(a)

[7522952325, 2020060669, 'Statistics', 'Aishwarya', 'F', 'M', 'F', 'M', 'M', 'M', 'F']


In [74]:
a.insert(5,"Ass.prof")
print(a)

[7522952325, 2020060669, 'Statistics', 'Aishwarya', 'F', 'Ass.prof', 'M', 'F', 'M', 'M', 'M', 'F']


In [75]:
a.pop(5)
print(a)

[7522952325, 2020060669, 'Statistics', 'Aishwarya', 'F', 'M', 'F', 'M', 'M', 'M', 'F']


In [76]:
a.pop()

'F'

In [77]:
print(a)

[7522952325, 2020060669, 'Statistics', 'Aishwarya', 'F', 'M', 'F', 'M', 'M', 'M']


In [78]:
a.remove("M")
print(a)

[7522952325, 2020060669, 'Statistics', 'Aishwarya', 'F', 'F', 'M', 'M', 'M']


In [79]:
a.reverse()
print(a)

['M', 'M', 'M', 'F', 'F', 'Aishwarya', 'Statistics', 2020060669, 7522952325]


In [80]:
a.sort()

TypeError: '<' not supported between instances of 'int' and 'str'

In [81]:
c=[100,56,28,34,184]

In [82]:
c.sort()
print(c)

[28, 34, 56, 100, 184]


In [83]:
c.sort(reverse=True)
print(c)

[184, 100, 56, 34, 28]


In [84]:
def myfun(e):
    return len(e)

cars=['Ford','BMW','Audi',"Hyundyai"]
#myfun(cars)
cars.sort(key=myfun)
cars

['BMW', 'Ford', 'Audi', 'Hyundyai']

In [85]:
cars.sort()
print(cars)

['Audi', 'BMW', 'Ford', 'Hyundyai']


In [86]:
cars.clear()
print(cars)

[]


In [87]:
x=[10,20,30,40,50]
x

[10, 20, 30, 40, 50]

In [88]:
x[0]=99

In [89]:
x

[99, 20, 30, 40, 50]

In [90]:
del x[2]
print(x)

[99, 20, 40, 50]


# Tuple

Tuples are enclosed with the parentheses. Tuple are immutable.

In [91]:
a=(24,"Aish","Stat","Satara")
b=("Phaltan",415523,"Maharashtra")

In [92]:
type(a) and type(b)

tuple

In [93]:
a[1]

'Aish'

In [94]:
a[1]="Aishwarya"

TypeError: 'tuple' object does not support item assignment

In [95]:
del a[1]

TypeError: 'tuple' object doesn't support item deletion

In [96]:
a[2:]

('Stat', 'Satara')

In [97]:
a[:2]

(24, 'Aish')

In [98]:
a[2:3:1]

('Stat',)

In [99]:
a

(24, 'Aish', 'Stat', 'Satara')

In [100]:
(age,name,Subject,Dist)=a

In [101]:
age

24

In [102]:
name

'Aish'

In [103]:
a+b

(24, 'Aish', 'Stat', 'Satara', 'Phaltan', 415523, 'Maharashtra')

In [104]:
a*2

(24, 'Aish', 'Stat', 'Satara', 24, 'Aish', 'Stat', 'Satara')

In [105]:
"Aish" in a

True

In [106]:
a.count("Aish")

1

In [107]:
a.index("Stat")

2

# Dictionary

Dictionary are used store data values in key value pairs.
Dictionaries have no concept of order among element. It is incorrect to say that the element are "out of order", they are simply unordered.
Dictionaries are changeable.

In [108]:
d={"Aish":85,"Gouri":70,"Harsh":90,"Nayan":75}

In [109]:
print(d)
type(d)

{'Aish': 85, 'Gouri': 70, 'Harsh': 90, 'Nayan': 75}


dict

In [110]:
d["Aish"]

85

In [111]:
d["Gouri"]

70

In [112]:
d["Aish"]=99

In [113]:
d

{'Aish': 99, 'Gouri': 70, 'Harsh': 90, 'Nayan': 75}

In [114]:
d["Aish"]==99

True

In [115]:
d["Aish"]!=99

False

In [116]:
del d["Nayan"]

In [117]:
d

{'Aish': 99, 'Gouri': 70, 'Harsh': 90}

In [118]:
len(d)

3

In [119]:
d={}


In [120]:
d["One"]="This is one"
d[2]="This is two"

In [121]:
d

{'One': 'This is one', 2: 'This is two'}

In [122]:
print(type(d))

<class 'dict'>


In [123]:
d["3"]="three"

In [124]:
d

{'One': 'This is one', 2: 'This is two', '3': 'three'}

In [125]:
"One" in d

True

In [126]:
x=("1","2")

In [127]:
y=("one","two")

In [128]:
a=dict.fromkeys(x)

In [129]:
print(a)

{'1': None, '2': None}


In [130]:
a=dict.fromkeys((1,2,3),0)
a

{1: 0, 2: 0, 3: 0}

In [131]:
x=("key1","key2","key3")

In [132]:
thisdict=dict.fromkeys(x)
print(thisdict)

{'key1': None, 'key2': None, 'key3': None}


In [133]:
d={"A":123,"B":456,"C":789,"D":135}

In [134]:
d.get("A")

123

In [135]:
d.get("E",999)

999

In [136]:
d

{'A': 123, 'B': 456, 'C': 789, 'D': 135}

In [137]:
d.items()

dict_items([('A', 123), ('B', 456), ('C', 789), ('D', 135)])

In [138]:
d.values()

dict_values([123, 456, 789, 135])

In [139]:
d.keys()

dict_keys(['A', 'B', 'C', 'D'])

In [140]:
d["XYZ"]=9999

In [141]:
d

{'A': 123, 'B': 456, 'C': 789, 'D': 135, 'XYZ': 9999}

In [142]:
print(d.pop("A"))

123


In [143]:
d

{'B': 456, 'C': 789, 'D': 135, 'XYZ': 9999}

In [144]:
print(d.pop("XYZ"))

9999


In [145]:
d

{'B': 456, 'C': 789, 'D': 135}

In [146]:
d.popitem()

('D', 135)

In [147]:
d

{'B': 456, 'C': 789}

In [148]:
print(d.setdefault("XYZ",77))
print(d)

77
{'B': 456, 'C': 789, 'XYZ': 77}


In [149]:
d.update({"AVR":155})
print(d)

{'B': 456, 'C': 789, 'XYZ': 77, 'AVR': 155}


# set

In [150]:
x={"A","D","d","s","f","M"}
x

{'A', 'D', 'M', 'd', 'f', 's'}

In [151]:
type(x)

set

In [152]:
emptyset=set()
emptyset

set()

In [153]:
x


{'A', 'D', 'M', 'd', 'f', 's'}

In [154]:
x.add("Y")

In [155]:
x

{'A', 'D', 'M', 'Y', 'd', 'f', 's'}

In [156]:
x_asi={"H","Y","M"}

In [157]:
print(x.difference(x_asi))

{'f', 'A', 'D', 's', 'd'}


In [158]:
print(x_asi.difference(x))

{'H'}


In [159]:
x={"HVK","DNK","SBM","SDP","SVK"}
print(x)

{'SBM', 'DNK', 'SDP', 'SVK', 'HVK'}


In [160]:
x_asi={"SDP","SVR"}

In [161]:
print(x.difference_update(x_asi))

None


In [162]:
print(x_asi.difference_update(x))

None


In [163]:
x

{'DNK', 'HVK', 'SBM', 'SVK'}

In [164]:
x_asi

{'SDP', 'SVR'}

In [165]:
x.discard("SVK")
print(x)

{'SBM', 'DNK', 'HVK'}


In [166]:
x.discard("PQR")
x

{'DNK', 'HVK', 'SBM'}

In [167]:
a={10,20,30,45,85,46}
b={10,52,60,30,45,74}

In [168]:
print(a.intersection(b))
print(b.intersection(a))

{10, 45, 30}
{10, 45, 30}


In [169]:
print(a.intersection_update(b))
print(a)

None
{10, 45, 30}


In [170]:
print(b)

{52, 74, 10, 60, 45, 30}


In [171]:
print(a)

{10, 45, 30}


In [172]:
x={"a","b","c"}
y={"c","d","e"}
f={"a","s","c"}

In [173]:
x.intersection(y,f)

{'c'}

In [174]:
x.union(y)
#print(x)
#print(y)

{'a', 'b', 'c', 'd', 'e'}

In [175]:
x.isdisjoint(y)

False

In [176]:
x.issubset(y)

False

In [177]:
print(x)
print(x.pop())
print(x)

{'c', 'a', 'b'}
c
{'a', 'b'}


In [178]:
print(y)
print(y.remove("e"))
print(y)

{'c', 'd', 'e'}
None
{'c', 'd'}


In [179]:
x={"H","D","S","SD","SV"}
xasi={"SD","SV","K"}

In [180]:
print(x.symmetric_difference(xasi))

{'S', 'K', 'D', 'H'}


In [181]:
x.update(xasi)

In [182]:
print(x)

{'D', 'SD', 'H', 'S', 'SV', 'K'}


# data type conversion

In [183]:
a=2.6
b=int(a)
b

2

In [184]:
float(b)

2.0

In [185]:
str(b)

'2'

In [186]:
complex(a)

(2.6+0j)

In [187]:
eval(str(b))

2

In [188]:
type(eval(str(b)))

int

In [189]:
type(eval("1"))

int

In [190]:
a="Aish"
tuple(a)

('A', 'i', 's', 'h')

In [191]:
a=[1,"Aish","F"]
print(type(a))
b=tuple(a)
print(b)
type(b)

<class 'list'>
(1, 'Aish', 'F')


tuple

# Python Built in functions

In [192]:
abs(-3.56)

3.56

In [193]:
abs(3+2j)

3.605551275463989

In [194]:
x=[-1]
abs(x)

TypeError: bad operand type for abs(): 'list'

In [195]:
x={-1}
abs(x)

TypeError: bad operand type for abs(): 'set'

In [196]:
x=(-1,-2)
abs(x)

TypeError: bad operand type for abs(): 'tuple'

In [197]:
a=[1,2,3,45,8]
b=(1,2,3,65,85,963)
c={1,52,879,2364789}
d={"a":25,"c":566,'d':65454}
e="Aishwarya"
print(len(a))
print(len(b))
print(len(c))
print(len(d))
print(len(e))

5
6
4
3
9


In [198]:
print(round(2.333))
print(round(2.5789412,5))

2
2.57894


In [199]:
print(sum(2,5,5))

TypeError: sum() takes at most 2 arguments (3 given)

In [200]:
a=[2,8,5,6]
b=(2,5,6,8)
c={2,58,69,12}
print(sum(a))
print(sum(b))
print(sum(c))

21
21
141


In [201]:
range(5)

range(0, 5)

In [202]:
x=range(6)
print(x)
for n in x:
    print(n)

range(0, 6)
0
1
2
3
4
5


In [203]:
for i in x:
    i=i*i
    print(i)
print("End of the loop")

0
1
4
9
16
25
End of the loop


In [204]:
x=range(-5,6)
for i in x:
    print(i)

-5
-4
-3
-2
-1
0
1
2
3
4
5


In [205]:
x=range(0,15,2)
for i in x:
    print(i)

0
2
4
6
8
10
12
14


In [206]:
x=[10,20,3,14,4,1,5]
y={"a","A","C"}
print(sorted(x))
print(sorted(y))
print(sorted(y,reverse=True))

[1, 3, 4, 5, 10, 14, 20]
['A', 'C', 'a']
['a', 'C', 'A']


In [207]:
x=input("Enter a number ")

Enter a number 54


In [208]:
x

'54'

In [209]:
a=("a","b","c","d","e","f")
x=slice(0,4)
print(a[x])
y=slice(0,6,2)
print(a[y])

('a', 'b', 'c', 'd')
('a', 'c', 'e')


In [210]:
dir(list)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [211]:
help(sum)

Help on built-in function sum in module builtins:

sum(iterable, /, start=0)
    Return the sum of a 'start' value (default: 0) plus an iterable of numbers
    
    When the iterable is empty, return the start value.
    This function is intended specifically for use with numeric values and may
    reject non-numeric types.



# Python flow control

In [212]:
num=3
if num>0:
    print(num, "is even function")
print("This is always printed.")

3 is even function
This is always printed.


In [213]:
num=-9
if num>=0:
    print(num," is positive number or zero")
else:
    print(num, "is negative number")

-9 is negative number


In [214]:
x=9
if x%2==0:
    print(x, "is even number")
else:
    print(x, "is odd number")

9 is odd number


In [215]:
num=25
if num>0:
    print(num, "is positive number")
elif num==0:
    print(num, "is zero")
else:
    print(num,"is negative number")

25 is positive number


# Python Nested if Statements

In [216]:
num=float(input("Enter your number:" ))
if num>=0:
    if  num==0:
        print(num,"zero")
    print(num,"Positive number")
else:
    print(num, "Negative number")

Enter your number:85
85.0 Positive number


In [217]:
num=[1,54,45,75,78]
sum=0
for i in num:
    sum=sum+i
print(sum)

253


In [218]:
num=[12,15,45,85,84,87,78]
val=[]
for i in num:
    if i%2==0:
        print(i)
        val.append(i)
print(val)

12
84
78
[12, 84, 78]


In [219]:
l=[20,25,30]
a=0
l[a]=10
l

[10, 25, 30]

In [220]:
for i in range(-5,10):
    print(i,i*i,i+1)

-5 25 -4
-4 16 -3
-3 9 -2
-2 4 -1
-1 1 0
0 0 1
1 1 2
2 4 3
3 9 4
4 16 5
5 25 6
6 36 7
7 49 8
8 64 9
9 81 10


# for loop with else

In [221]:
digit=[1,5,9]
for i in digit:
    print(i)
else:
    print('no item left')

1
5
9
no item left


In [222]:
student_name="Jin"
marks={"RM":100,"Suga":100,"Jin":99,"Jhope":98}
for i in marks:
    if i==student_name:
        print(marks[student_name])
        break
else:
    print("No entry with that name found")

99


# Nested Loops

In [223]:
vocal=["jin","jimin","v","JK"]
rapper=["RM","suga","jhope"]
for i in vocal:
    for j in rapper:
        print(i,j)

jin RM
jin suga
jin jhope
jimin RM
jimin suga
jimin jhope
v RM
v suga
v jhope
JK RM
JK suga
JK jhope


In [224]:
#program to add natural number upto sum=1+2+3+...+n
#To take input from the user, n=int(input("Enter n: "))
n=int(input("Enter n: "))
#initalize sum and counter
sum=0
i=1
while i<=n:
    sum=sum+i
    i=i+1
print(sum)

Enter n: 85
3655


In [225]:
# sum of n natural number, then take square
n=5
sum=0
i=1
sq=0
while i<=n:
    sum=sum+i
    sq=sum**2
    i=i+1
print(sum)
print(sq)

15
225


In [226]:
counter=6
while counter <7:
    print("Inside loop")
    counter=counter+1
    break
else:
    print("Inside else")

Inside loop


# Break statement in Python

In [227]:
for i in "Aishwarya":
    if i=="y":
        break
    print(i)
print("The End")

A
i
s
h
w
a
r
The End


# Continue statement

In [228]:
for i in "Aishwarya":
    if i=="y":
        continue
    print(i)
print("The end")

A
i
s
h
w
a
r
a
The end


# Loop using list comprehension

In [229]:
bts=["rm","jin","suga","jhope","jimin","v","jk"]
new=[x for x in bts if "j" in x]
print(new)

['jin', 'jhope', 'jimin', 'jk']


In [230]:
new=[x for x in range(0,10)]
print(new)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [231]:
new=[i for i in range(0,10) if i<5]
print(new)

[0, 1, 2, 3, 4]


In [232]:
bts=["rm","jin","suga","jhope","jimin","v","jk"]
new=[x.upper() for x in bts]
print(new)

['RM', 'JIN', 'SUGA', 'JHOPE', 'JIMIN', 'V', 'JK']


In [233]:
bts=["rm","jin","suga","jhope","jimin","v","jk"]
new=[x if x!="rm" else "namjoon"for x in bts]
print(new)

['namjoon', 'jin', 'suga', 'jhope', 'jimin', 'v', 'jk']


# loop th' dictionary

In [234]:
bts={"rm":'leader',"jin":'visual',"suga":"producer","jhope":"main dancer","jimin":"dancer+vocal","v":"visual+main vocal","jk":"main dancer+ visidual+main vocal"}
for i in bts:
    print(i)


rm
jin
suga
jhope
jimin
v
jk


In [235]:
bts={"rm":'leader',"jin":'visual',"suga":"producer","jhope":"main dancer","jimin":"dancer+vocal","v":"visual+main vocal","jk":"main dancer+ visidual+main vocal"}
for i in bts:
    print(bts[i])

leader
visual
producer
main dancer
dancer+vocal
visual+main vocal
main dancer+ visidual+main vocal


In [236]:
for i in bts.values():
    print(i)

leader
visual
producer
main dancer
dancer+vocal
visual+main vocal
main dancer+ visidual+main vocal


In [237]:
for i,j in bts.items():
    print(i,j)

rm leader
jin visual
suga producer
jhope main dancer
jimin dancer+vocal
v visual+main vocal
jk main dancer+ visidual+main vocal


In [238]:
# loop th' set
# in set loop arrange strings alphabetically.
bts={"rm","jin","suga","jhope","jimin","v","jk"}
for i in bts:
    print(i)

suga
v
jimin
rm
jhope
jk
jin


# python functions

In [239]:
# factorial self define function
def fact(n):
    f=1
    for i in range(1,n+1):
        f=f*i
    return(f)
fact(4)

24

In [240]:
fact(15)

1307674368000

In [248]:
def nck(n,k):
    return(fact(n)/(fact(k)*fact(n-k)))

In [249]:
nck(3,2)

3.0

In [250]:
# self define function for mean
def mean(x):
    n=len(x)
    s=0
    for i in range(n):
        s=s+x[i]
    return(s/n)

In [255]:
x=[1,56,89,7412]
print(mean(x))
var(x)

1889.5


40667961.0

In [256]:
# self def function for variance
def var(x):
    n=len(x)
    s=0
    xm=mean(x)
    for i in range(n):
        s=s+(x[i]-xm)**2
    return(s)

In [257]:
#self def function for maximum value
def maximum(a,b):
    if a>=b:
        return(a)
    else:
        return(b)
    
maximum(2,3)

3

In [258]:
#self def function for minimum value
def minimum(a,b):
    if a>=b:
        return(b)
    else:
        return(a)

minimum(2,3)

2

In [260]:
import math
dir(math)

['__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'ceil',
 'comb',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'dist',
 'e',
 'erf',
 'erfc',
 'exp',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'isqrt',
 'lcm',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'nextafter',
 'perm',
 'pi',
 'pow',
 'prod',
 'radians',
 'remainder',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'tau',
 'trunc',
 'ulp']

In [261]:
import numpy as np

In [262]:
xx=np.array([1,4,3,2,5,3])

In [263]:
x="1"

In [265]:
y="2"
z=x+y
print(z)
type(z)

12


str

In [266]:
np.array([3.14,4,2,3])

array([3.14, 4.  , 2.  , 3.  ])

In [267]:
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [268]:
print(np.zeros(10,dtype=int))

[0 0 0 0 0 0 0 0 0 0]


In [269]:
print(np.zeros((2,4),dtype=int))

[[0 0 0 0]
 [0 0 0 0]]


In [270]:
a=np.ones(4)

In [271]:
a

array([1., 1., 1., 1.])

In [272]:
a=np.ones(4,dtype=int)
print(a)

[1 1 1 1]


In [274]:
a=np.ones((3,1),dtype=float)
b=np.full((3,2),56)
print(a)
print(b)

[[1.]
 [1.]
 [1.]]
[[56 56]
 [56 56]
 [56 56]]


In [275]:
np.arange(0,1,5)

array([0])

In [276]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [277]:
np.linspace(1,100,100)

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100.])